/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import guitar.common.SQLiteJDBC;
import guitar.dao.GuitarDao;
import guitar.dao.impl.GuitarDaoimpl;
import guitar.domain.Guitar;
import guitar.domain.GuitarSpec;
import guitar.service.GuitarService;
import guitar.service.impl.GuitarServiceimpl;

import static org.junit.Assert.*;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;

public class GuitarSpecServiceimplTest {
	@Test
	public void Search(){
		Guitar searchGuitar=new Guitar("11277", 1499.95,new GuitarSpec("Collings", "CJ", "acoustic", 12, "Indian Rosewood", "Sitka")); 
		GuitarService GuitarService=new GuitarServiceimpl();
		GuitarService.Search(searchGuitar);		
		System.out.println(GuitarService.Search(searchGuitar).get(0).getPrice());
	}
	@Test
	public void Search2(){
		Guitar searchGuitar=new Guitar("11277", 1499.95,new GuitarSpec("Collings", "CJ", "acoustic", 12, "Indian Rosewood", "Sitka")); 
		GuitarServiceimpl GuitarServiceimpl=new GuitarServiceimpl();
		GuitarDaoimpl GuitarDaoimpl=new GuitarDaoimpl();
		GuitarServiceimpl.setGuitarDao(GuitarDaoimpl);
		GuitarServiceimpl.Search(searchGuitar);		
		System.out.println(GuitarServiceimpl.Search(searchGuitar).get(0).getPrice());
		System.out.println("serialNumber: "+GuitarServiceimpl.Search(searchGuitar).get(0).getSerialNumber());
		System.out.println("price: "+GuitarServiceimpl.Search(searchGuitar).get(0).getPrice());
		System.out.println("builder: "+GuitarServiceimpl.Search(searchGuitar).get(0).getSpec().getBuilder());
		System.out.println("model: "+GuitarServiceimpl.Search(searchGuitar).get(0).getSpec().getModel());
		System.out.println("numStrings: "+GuitarServiceimpl.Search(searchGuitar).get(0).getSpec().getNumStrings());
		System.out.println("type: "+GuitarServiceimpl.Search(searchGuitar).get(0).getSpec().getType());
		System.out.println("backWood: "+GuitarServiceimpl.Search(searchGuitar).get(0).getSpec().getBackWood());
		System.out.println("topWood: "+GuitarServiceimpl.Search(searchGuitar).get(0).getSpec().getTopWood());
	}
	
		
}
